name: publish-icons
on:
  push:
    branches:
    - 'master'
    paths:
    - 'package.json'

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Setup publish
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@rancher'

      # Ensure latest npm version is installed - 11.5.1 is required to pass OIDC token to npm publish
      - name: Update npm
        run: npm install -g npm@latest

      - name: Run publish script
        run: |
          git config --global user.name 'Rancher Icons'
          git config --global user.email 'noreply@rancher.com'
          yarn install
          yarn run upload -i