name: publish-icons
on:
  push:
    branches:
    - 'master'
    paths:
    - 'package.json'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup publish
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #v6.3.0
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@rancher'

      # Ensure latest npm version is installed - 11.5.1 is required to pass OIDC token to npm publish
      - name: Update npm
        run: npm install -g npm@latest

      - name: Run publish script     
        run: |
          git config --global user.name 'Rancher Icons'
          git config --global user.email 'noreply@rancher.com'
          yarn install
          yarn run upload -i
